version: "3.3"

services:
  app:
    build: .
    volumes:
      - './:/app'
    image: emiliano/app
    networks:
      - default
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 20s
        window: 120s
    restart: always
    ports:
      - '4563:3000'
